### ISSUE TITLE
About train and test on real SAR image

### ISSUE THREAD

**Issue by longbai1006** [malshaV/sar_transformer#1]
Thank you for your nice work!

I am a bit confused about the training setup on real SAR data. You mentioned real SAR image data does not have clean ground truth data. In this case, did you train your model on synthetically generated speckled images, and then directly test your model on real SAR image data? Thank you very much!

**Comment by malshaV** [comment]
Yes, the model is trained on synthetic images and tested on both synthetic and real images

**Comment by longbai1006** [comment]
Thanks a lot!
