### ISSUE TITLE
About the PSNR and SSIM calculation

### ISSUE THREAD

**Issue by zmxkzserz65** [malshaV/sar_transformer#5]
After reproducing your method and testing on the images of Folder(test_images), we calculate the PSNR and SSIM of the corresponding images by skimage method(from skimage.measure import compare_ssim, compare_psnr). The results are 
test_01: 17.681737630664713 | 0.2879361900735046
test_02: 18.692031701593233 | 0.3217149449483932
respectively, which is far away from your result: 24.56 | 0.718. 
What's the problem?

**Comment by malshaV** [comment]
The test images are real SAR images and they do not have ground truth. Hence, it is not possible to calculate PSNR and SSIM on these images. The PSNR and SSIM presented on the paper is calculated on a different synthetic dataset.

**Comment by zmxkzserz65** [comment]
Sorry, I made a mistake. I followed your method of testing on the Set12 dataset and the results are close. 
My research is about cross domain few shot learning on SAR images which put the SAR images as input of the network. I found that the visual difference between original image and denoised image is not ignorable, and the result of CDFSL experiments on denoised MSTAR dataset by your method is not as good as the original. Could you give me some advice? Hoping for your reply.
